fix(lint): shellfmt

diff --git a/install b/install
--- a/install
+++ b/install
@@ -128,7 +128,7 @@ BINARY="$FOUNDRY_BIN_DIR/foundryup"
 
 # Create the .foundry bin directory and foundryup binary if it doesn't exist.
 mkdir -p "$FOUNDRY_BIN_DIR"
-echo "$FOUNDRYUP" > "$BINARY"
+echo "$FOUNDRYUP" >"$BINARY"
 chmod +x "$BINARY"
 
 # Create the man directory for future man files if it doesn't exist.
@@ -137,30 +137,31 @@ mkdir -p "$FOUNDRY_MAN_DIR"
 # Store the correct profile file (i.e. .profile for bash or .zshrc for ZSH).
 case $SHELL in
 */zsh)
-    PROFILE=$HOME/.zshrc
-    PREF_SHELL=zsh
-    ;;
+	PROFILE=$HOME/.zshrc
+	PREF_SHELL=zsh
+	;;
 */bash)
-    PROFILE=$HOME/.bashrc
-    PREF_SHELL=bash
-    ;;
+	PROFILE=$HOME/.bashrc
+	PREF_SHELL=bash
+	;;
 */fish)
-    PROFILE=$HOME/.config/fish/config.fish
-    PREF_SHELL=fish
-    ;;
+	PROFILE=$HOME/.config/fish/config.fish
+	PREF_SHELL=fish
+	;;
 *)
-    echo "foundryup: could not detect shell, manually add ${FOUNDRY_BIN_DIR} to your PATH."
-    exit 1
+	echo "foundryup: could not detect shell, manually add ${FOUNDRY_BIN_DIR} to your PATH."
+	exit 1
+	;;
 
 esac
 
 # Only add foundryup if it isn't already in PATH.
 if [[ ":$PATH:" != *":${FOUNDRY_BIN_DIR}:"* ]]; then
-if [[ $OSTYPE == 'darwin'* ]]; then
-    echo >> "$HOME"/.bash_profile && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >> $$HOME/.bash_profile
-fi 
-    # Add the foundryup directory to the path and ensure the old PATH variables remain.
-    echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >> "$PROFILE"
+	if [[ $OSTYPE == 'darwin'* ]]; then
+		echo >>"$HOME"/.bash_profile && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >>$$HOME/.bash_profile
+	fi
+	# Add the foundryup directory to the path and ensure the old PATH variables remain.
+	echo >>"$PROFILE" && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >>"$PROFILE"
 fi
 
 echo && echo "Detected your preferred shell is ${PREF_SHELL} and added foundryup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use foundryup."
